In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [31]:
pip install alpaca-trade-api

Requirement already satisfied: alpaca-trade-api in /usr/local/lib/python3.11/dist-packages (3.2.0)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.2.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.0.2)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.32.3)
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.8.0)
Requirement already satisfied: websockets<11,>=9.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (10.4)
Requirement already satisfied: msgpack==1.0.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.0.3)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (3.11.15)
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from deprecation==2.1.0->alpaca-trade-api) (24.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.20.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.18.1->alpaca-trade-api) (1.17.0)

In [32]:
pip install polygon-api-client

Requirement already satisfied: polygon-api-client in /usr/local/lib/python3.11/dist-packages (1.14.5)
Requirement already satisfied: certifi<2026.0.0,>=2022.5.18 in /usr/local/lib/python3.11/dist-packages (from polygon-api-client) (2025.1.31)
Requirement already satisfied: urllib3<3.0.0,>=1.26.9 in /usr/local/lib/python3.11/dist-packages (from polygon-api-client) (1.26.20)
Requirement already satisfied: websockets<15.0,>=10.3 in /usr/local/lib/python3.11/dist-packages (from polygon-api-client) (10.4)

In [33]:
import alpaca_trade_api as tradeapi
from polygon import RESTClient
import pandas as pd
import time
from datetime import datetime, timedelta, timezone
import tensorflow as tf
from tensorflow.keras.models import load_model
import joblib
import numpy as np

In [ ]:
ALPACA_API_KEY = "[...]"
ALPACA_SECRET_KEY = "[...]"
ALPACA_BASE_URL = "https://api.alpaca.markets"

POLYGON_API_KEY = "[...]"

In [35]:
# Inicializa a API Alpaca com as credenciais lidas do arquivo
api = tradeapi.REST(ALPACA_API_KEY, ALPACA_SECRET_KEY, ALPACA_BASE_URL, api_version='v2')

In [36]:
clock = api.get_clock()

In [37]:
clock

Clock({   'is_open': True,
    'next_close': '2025-04-29T16:00:00-04:00',
    'next_open': '2025-04-30T09:30:00-04:00',
    'timestamp': '2025-04-29T13:13:14.204470358-04:00'})

In [38]:
client = RESTClient(POLYGON_API_KEY)

In [39]:
status = client.get_market_status()

In [40]:
status

MarketStatus(after_hours=False, currencies=MarketCurrencies(crypto='open', fx='open'), early_hours=False, exchanges=MarketExchanges(nasdaq='open', nyse='open', otc='open'), indicesGroups=MarketIndices(s_and_p='open', societe_generale='open', cgi='open', msci='open', ftse_russell='open', mstar='open', mstarc='open', cccy='open', nasdaq='open', dow_jones='open'), market='open', server_time='2025-04-29T13:13:14-04:00')

In [41]:
if status.market == "open":
    print("The market is open regular hours.")
elif status.pearly_hours:
    print("The market is open pre hours.")
elif status.after_hours:
    print("The market is open after hours.")
else:
    print("The market is closed.")

The market is open regular hours.

In [42]:
delayed_safe_df = 5

now   = datetime.now(timezone.utc)
start = (now - timedelta(days=delayed_safe_df)).isoformat()

print("Now (UTC):", now)
print("Start (UTC):", start)

Now (UTC): 2025-04-29 17:13:14.609314+00:00
Start (UTC): 2025-04-24T17:13:14.609314+00:00

In [43]:
symbol = "AAPL"
timeframe = "5Min"
data_source = "sip"
dataset_size = 36

In [44]:
# Fetch the historical data
bars = api.get_bars(
    symbol,
    timeframe,
    start,
    feed=data_source
).df.tail(dataset_size)

In [45]:
bars

,close,high,low,trade_count,open,volume,vwap
timestamp,,,,,,,
2025-04-29 14:00:00+00:00,210.8900,211.0000,210.3300,8821,210.8100,413425,210.664221
2025-04-29 14:05:00+00:00,211.5100,211.8400,210.8400,9289,210.8800,546991,211.582703
2025-04-29 14:10:00+00:00,212.0200,212.1090,211.5100,10518,211.5100,758298,211.850167
2025-04-29 14:15:00+00:00,211.2600,212.2400,211.1500,10047,212.0150,605568,211.681098
2025-04-29 14:20:00+00:00,211.0812,211.4100,210.9800,6455,211.2400,376585,211.155843
2025-04-29 14:25:00+00:00,210.9500,211.2200,210.7000,5446,211.0730,317716,210.904705
2025-04-29 14:30:00+00:00,211.1000,211.2000,210.8400,5462,210.9600,284823,211.014102
2025-04-29 14:35:00+00:00,211.3200,211.4900,211.0200,5160,211.1000,249223,211.330045
2025-04-29 14:40:00+00:00,211.2300,211.4498,211.1300,5594,211.3450,289036,211.309857
2025-04-29 14:45:00+00:00,211.5303,211.6997,211.2050,4900,211.2450,290236,211.515173
2025-04-29 14:50:00+00:00,211.8300,211.8800,211.3300,4992,211.5444,343185,211.595746
2025-04-29 14:55:00+00:00,211.6111,212.0700,211.5721,5105,211.8400,298527,211.875685
2025-04-29 15:00:00+00:00,211.4608,211.8000,211.2700,4611,211.6200,266265,211.593370
2025-04-29 15:05:00+00:00,211.3500,211.5700,211.1600,3792,211.4700,219275,211.435944
2025-04-29 15:10:00+00:00,211.1282,211.3600,210.9300,3965,211.3550,242822,211.122684
2025-04-29 15:15:00+00:00,210.7700,211.2300,210.7101,4012,211.1200,215436,210.983397
2025-04-29 15:20:00+00:00,210.6900,211.0800,210.6700,4019,210.7800,240011,210.832742
2025-04-29 15:25:00+00:00,211.0400,211.1800,210.6935,4400,210.7000,279714,210.991218
2025-04-29 15:30:00+00:00,210.6400,211.1400,210.4000,5500,211.0400,723598,210.661500
2025-04-29 15:35:00+00:00,210.7964,210.9650,210.4500,3791,210.6300,210829,210.751646
2025-04-29 15:40:00+00:00,211.1600,211.1710,210.7600,3241,210.8200,155522,210.995749
2025-04-29 15:45:00+00:00,210.8935,211.2100,210.7600,3032,211.1500,138412,211.020632
2025-04-29 15:50:00+00:00,210.7900,211.0250,210.6000,2966,210.9050,158209,210.818868
2025-04-29 15:55:00+00:00,210.6150,210.8897,210.5101,2988,210.7400,153763,210.682832
2025-04-29 16:00:00+00:00,210.9800,211.0000,210.6150,3623,210.6150,166187,210.827225
2025-04-29 16:05:00+00:00,211.2009,211.3253,210.9800,3452,210.9900,179306,211.164448
2025-04-29 16:10:00+00:00,210.8600,211.2429,210.8400,3707,211.2100,201687,211.066550
2025-04-29 16:15:00+00:00,210.6007,210.9100,210.5200,3559,210.8700,213917,210.751198
2025-04-29 16:20:00+00:00,210.5750,210.7800,210.5201,2882,210.6000,151640,210.649921
2025-04-29 16:25:00+00:00,210.4880,210.6799,210.4200,3723,210.5600,216319,210.521722
2025-04-29 16:30:00+00:00,210.4900,210.5400,210.2800,4450,210.4700,283691,210.425704
2025-04-29 16:35:00+00:00,210.2200,210.6193,210.1200,3988,210.5000,241130,210.410009
2025-04-29 16:40:00+00:00,210.5150,210.6200,210.2200,2973,210.2250,183047,210.466793
2025-04-29 16:45:00+00:00,209.8500,210.5200,209.6600,4980,210.5000,277701,210.094607
2025-04-29 16:50:00+00:00,210.0050,210.0966,209.7300,3125,209.8624,180218,209.958355
2025-04-29 16:55:00+00:00,209.7326,210.0300,209.3500,4893,210.0100,295857,209.606371

In [46]:
data = bars[['vwap', 'trade_count']]

In [47]:
data

                                 vwap  trade_count
timestamp
2025-04-29 14:00:00+00:00  210.664221         8821
2025-04-29 14:05:00+00:00  211.582703         9289
2025-04-29 14:10:00+00:00  211.850167        10518
2025-04-29 14:15:00+00:00  211.681098        10047
2025-04-29 14:20:00+00:00  211.155843         6455
2025-04-29 14:25:00+00:00  210.904705         5446
2025-04-29 14:30:00+00:00  211.014102         5462
2025-04-29 14:35:00+00:00  211.330045         5160
2025-04-29 14:40:00+00:00  211.309857         5594
2025-04-29 14:45:00+00:00  211.515173         4900
2025-04-29 14:50:00+00:00  211.595746         4992
2025-04-29 14:55:00+00:00  211.875685         5105
2025-04-29 15:00:00+00:00  211.593370         4611
2025-04-29 15:05:00+00:00  211.435944         3792
2025-04-29 15:10:00+00:00  211.122684         3965
2025-04-29 15:15:00+00:00  210.983397         4012
2025-04-29 15:20:00+00:00  210.832742         4019
2025-04-29 15:25:00+00:00  210.991218         4400
2025-04-29 15:30:00+00:00  210.661500         5500
2025-04-29 15:35:00+00:00  210.751646         3791
2025-04-29 15:40:00+00:00  210.995749         3241
2025-04-29 15:45:00+00:00  211.020632         3032
2025-04-29 15:50:00+00:00  210.818868         2966
2025-04-29 15:55:00+00:00  210.682832         2988
2025-04-29 16:00:00+00:00  210.827225         3623
2025-04-29 16:05:00+00:00  211.164448         3452
2025-04-29 16:10:00+00:00  211.066550         3707
2025-04-29 16:15:00+00:00  210.751198         3559
2025-04-29 16:20:00+00:00  210.649921         2882
2025-04-29 16:25:00+00:00  210.521722         3723
2025-04-29 16:30:00+00:00  210.425704         4450
2025-04-29 16:35:00+00:00  210.410009         3988
2025-04-29 16:40:00+00:00  210.466793         2973
2025-04-29 16:45:00+00:00  210.094607         4980
2025-04-29 16:50:00+00:00  209.958355         3125
2025-04-29 16:55:00+00:00  209.606371         4893

In [ ]:
scaler = joblib.load("[...]")

In [49]:
X_VWAP = data[['vwap']].to_numpy()

X_VWAP_scaled = scaler.transform(X_VWAP)

In [50]:
X_VWAP_scaled

array([[0.28496234],
       [0.28712056],
       [0.28774903],
       [0.28735176],
       [0.28611754],
       [0.28552742],
       [0.28578448],
       [0.28652687],
       [0.28647943],
       [0.28696188],
       [0.2871512 ],
       [0.28780899],
       [0.28714562],
       [0.28677571],
       [0.28603962],
       [0.28571233],
       [0.28535833],
       [0.28573071],
       [0.28495595],
       [0.28516777],
       [0.28574136],
       [0.28579982],
       [0.28532573],
       [0.28500608],
       [0.28534536],
       [0.28613776],
       [0.28590772],
       [0.28516672],
       [0.28492874],
       [0.28462751],
       [0.28440189],
       [0.28436501],
       [0.28449844],
       [0.28362389],
       [0.28330373],
       [0.28247665]])

In [51]:
X_Trade_Count = data[['trade_count']].to_numpy()

In [52]:
X_Trade_Count

array([[ 8821],
       [ 9289],
       [10518],
       [10047],
       [ 6455],
       [ 5446],
       [ 5462],
       [ 5160],
       [ 5594],
       [ 4900],
       [ 4992],
       [ 5105],
       [ 4611],
       [ 3792],
       [ 3965],
       [ 4012],
       [ 4019],
       [ 4400],
       [ 5500],
       [ 3791],
       [ 3241],
       [ 3032],
       [ 2966],
       [ 2988],
       [ 3623],
       [ 3452],
       [ 3707],
       [ 3559],
       [ 2882],
       [ 3723],
       [ 4450],
       [ 3988],
       [ 2973],
       [ 4980],
       [ 3125],
       [ 4893]])

In [53]:
X_combined = np.concatenate([X_VWAP_scaled, X_Trade_Count], axis=1)

In [54]:
X_combined

array([[2.84962344e-01, 8.82100000e+03],
       [2.87120556e-01, 9.28900000e+03],
       [2.87749032e-01, 1.05180000e+04],
       [2.87351760e-01, 1.00470000e+04],
       [2.86117538e-01, 6.45500000e+03],
       [2.85527424e-01, 5.44600000e+03],
       [2.85784480e-01, 5.46200000e+03],
       [2.86526870e-01, 5.16000000e+03],
       [2.86479433e-01, 5.59400000e+03],
       [2.86961877e-01, 4.90000000e+03],
       [2.87151204e-01, 4.99200000e+03],
       [2.87808993e-01, 5.10500000e+03],
       [2.87145621e-01, 4.61100000e+03],
       [2.86775708e-01, 3.79200000e+03],
       [2.86039622e-01, 3.96500000e+03],
       [2.85712331e-01, 4.01200000e+03],
       [2.85358328e-01, 4.01900000e+03],
       [2.85730709e-01, 4.40000000e+03],
       [2.84955951e-01, 5.50000000e+03],
       [2.85167772e-01, 3.79100000e+03],
       [2.85741355e-01, 3.24100000e+03],
       [2.85799824e-01, 3.03200000e+03],
       [2.85325727e-01, 2.96600000e+03],
       [2.85006076e-01, 2.98800000e+03],
       [2.85345364e-01, 3.62300000e+03],
       [2.86137757e-01, 3.45200000e+03],
       [2.85907721e-01, 3.70700000e+03],
       [2.85166719e-01, 3.55900000e+03],
       [2.84928743e-01, 2.88200000e+03],
       [2.84627506e-01, 3.72300000e+03],
       [2.84401887e-01, 4.45000000e+03],
       [2.84365007e-01, 3.98800000e+03],
       [2.84498436e-01, 2.97300000e+03],
       [2.83623888e-01, 4.98000000e+03],
       [2.83303729e-01, 3.12500000e+03],
       [2.82476651e-01, 4.89300000e+03]])

In [55]:
X_Tensor = np.expand_dims(X_combined, axis=0)

In [56]:
X_Tensor

array([[[2.84962344e-01, 8.82100000e+03],
        [2.87120556e-01, 9.28900000e+03],
        [2.87749032e-01, 1.05180000e+04],
        [2.87351760e-01, 1.00470000e+04],
        [2.86117538e-01, 6.45500000e+03],
        [2.85527424e-01, 5.44600000e+03],
        [2.85784480e-01, 5.46200000e+03],
        [2.86526870e-01, 5.16000000e+03],
        [2.86479433e-01, 5.59400000e+03],
        [2.86961877e-01, 4.90000000e+03],
        [2.87151204e-01, 4.99200000e+03],
        [2.87808993e-01, 5.10500000e+03],
        [2.87145621e-01, 4.61100000e+03],
        [2.86775708e-01, 3.79200000e+03],
        [2.86039622e-01, 3.96500000e+03],
        [2.85712331e-01, 4.01200000e+03],
        [2.85358328e-01, 4.01900000e+03],
        [2.85730709e-01, 4.40000000e+03],
        [2.84955951e-01, 5.50000000e+03],
        [2.85167772e-01, 3.79100000e+03],
        [2.85741355e-01, 3.24100000e+03],
        [2.85799824e-01, 3.03200000e+03],
        [2.85325727e-01, 2.96600000e+03],
        [2.85006076e-01, 2.98800000e+03],
        [2.85345364e-01, 3.62300000e+03],
        [2.86137757e-01, 3.45200000e+03],
        [2.85907721e-01, 3.70700000e+03],
        [2.85166719e-01, 3.55900000e+03],
        [2.84928743e-01, 2.88200000e+03],
        [2.84627506e-01, 3.72300000e+03],
        [2.84401887e-01, 4.45000000e+03],
        [2.84365007e-01, 3.98800000e+03],
        [2.84498436e-01, 2.97300000e+03],
        [2.83623888e-01, 4.98000000e+03],
        [2.83303729e-01, 3.12500000e+03],
        [2.82476651e-01, 4.89300000e+03]]])

In [ ]:
model = load_model("[...]")

In [58]:
predictions = model.predict(X_Tensor)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 984ms/step

In [59]:
predictions

array([[0.2409385]], dtype=float32)

In [60]:
decisive_sensibility = 0.5

predicted_classes = (predictions >= decisive_sensibility).astype(int)

In [61]:
print(predictions)
print(predicted_classes)

[[0.2409385]]
[[0]]