In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
pip install alpaca-trade-api

Collecting alpaca-trade-api
  Downloading alpaca_trade_api-3.2.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.2.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.0.2)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.32.3)
Collecting urllib3<2,>1.24 (from alpaca-trade-api)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.8.0)
Collecting websockets<11,>=9.0 (from alpaca-trade-api)
  Downloading websockets-10.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting msgpack==1.0.3 (from alpaca-trade-api)
  Downloading msgpack-1.0.3.tar.gz (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.8/123.8 kB 6.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (3.11.15)
Collecting PyYAML==6.0.1 (from alpaca-trade-api)
  Downloading PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting deprecation==2.1.0 (from alpaca-trade-api)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from deprecation==2.1.0->alpaca-trade-api) (24.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.19.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.18.1->alpaca-trade-api) (1.17.0)
Downloading alpaca_trade_api-3.2.0-py3-none-any.whl (34 kB)
Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Downloading PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.7/757.7 kB 23.1 MB/s eta 0:00:00
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 1.8 MB/s eta 0:00:00
Downloading websockets-10.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.4/107.4 kB 7.1 MB/s eta 0:00:00
Building wheels for collected packages: msgpack
  Building wheel for msgpack (setup.py) ... done
  Created wheel for msgpack: filename=msgpack-1.0.3-cp311-cp311-linux_x86_64.whl size=15688 sha256=bf45ef7a51862d4193fb985dc8585d47c2bdc5afb930ac773b092b7d76932f8c
  Stored in directory: /root/.cache/pip/wheels/f6/35/da/ed9b26b510235e00e3a3c3bab7bad97b59214729662255ab3d
Successfully built msgpack
Installing collected packages: msgpack, websockets, urllib3, PyYAML, deprecation, alpaca-trade-api
  Attempting uninstall: msgpack
    Found existing installation: msgpack 1.1.0
    Uninstalling msgpack-1.1.0:
      Successfully uninstalled msgpack-1.1.0
  Attempting uninstall: websockets
    Found existing installation: websockets 15.0.1
    Uninstalling websockets-15.0.1:
      Successfully uninstalled websockets-15.0.1
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.3.0
    Uninstalling urllib3-2.3.0:
      Successfully uninstalled urllib3-2.3.0
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.2
    Uninstalling PyYAML-6.0.2:
      Successfully uninstalled PyYAML-6.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-genai 1.10.0 requires websockets<15.1.0,>=13.0.0, but you have websockets 10.4 which is incompatible.
Successfully installed PyYAML-6.0.1 alpaca-trade-api-3.2.0 deprecation-2.1.0 msgpack-1.0.3 urllib3-1.26.20 websockets-10.4

In [3]:
import alpaca_trade_api as tradeapi
import pandas as pd
import time
from datetime import datetime, timedelta, timezone
import tensorflow as tf
from tensorflow.keras.models import load_model
import joblib
import numpy as np

In [4]:
API_KEY = "AK1RX6F8W6QX207XPLDF"
SECRET_KEY = "WaPoTTxkQBGzC51LajCdyw8Pl6svbINa9eDu9TMK"
BASE_URL = "https://api.alpaca.markets"

In [5]:
# Inicializa a API Alpaca com as credenciais lidas do arquivo
api = tradeapi.REST(API_KEY, SECRET_KEY, BASE_URL, api_version='v2')

In [6]:
symbol = "AAPL"
timeframe = "5Min"
data_source = "sip"

In [7]:
clock = api.get_clock()

In [8]:
clock

Clock({   'is_open': True,
    'next_close': '2025-04-22T16:00:00-04:00',
    'next_open': '2025-04-23T09:30:00-04:00',
    'timestamp': '2025-04-22T11:53:44.730241131-04:00'})

In [9]:
# Example: UTC timestamps with 'Z'
now   = datetime.now(timezone.utc)
start = (now - timedelta(hours=3) - timedelta(minutes=15)).isoformat()  # ⇒ '2025-04-21T12:49:12.774699+00:00'
end   = (now - timedelta(minutes=15)).isoformat()  # ⇒ '2025-04-21T13:34:12.774699+00:00'

print("Now (UTC):", now)
print("Start (UTC):", start)
print("End   (UTC):", end)

Now (UTC): 2025-04-22 15:53:47.654737+00:00
Start (UTC): 2025-04-22T12:38:47.654737+00:00
End   (UTC): 2025-04-22T15:38:47.654737+00:00

In [10]:
# Fetch the historical data
bars = api.get_bars(
    symbol,
    timeframe,
    start,
    end,
    feed=data_source
).df

In [11]:
bars

,close,high,low,trade_count,open,volume,vwap
timestamp,,,,,,,
2025-04-22 12:40:00+00:00,194.6900,194.6900,194.5000,245,194.6000,7573,194.587820
2025-04-22 12:45:00+00:00,194.8900,194.9100,194.6500,314,194.6900,28560,194.791148
2025-04-22 12:50:00+00:00,195.0900,195.1291,194.8706,307,194.9000,19954,194.947509
2025-04-22 12:55:00+00:00,195.1900,195.2000,195.0001,265,195.1000,13374,195.150332
2025-04-22 13:00:00+00:00,195.0900,195.2000,195.0400,278,195.1500,10692,195.157991
2025-04-22 13:05:00+00:00,195.0000,195.1600,194.9000,347,195.1600,17633,195.049877
2025-04-22 13:10:00+00:00,195.1000,195.1000,194.8319,379,194.9011,87636,194.948749
2025-04-22 13:15:00+00:00,194.9600,195.0999,194.9200,237,195.0999,9636,194.997318
2025-04-22 13:20:00+00:00,195.1400,195.1400,194.7300,471,194.9400,28267,195.006702
2025-04-22 13:25:00+00:00,196.0000,196.2890,195.1400,1039,195.1600,79413,195.775389
2025-04-22 13:30:00+00:00,196.8550,197.4500,195.9700,26689,196.0000,1933279,196.528102
2025-04-22 13:35:00+00:00,196.7200,196.9900,196.0900,10280,196.8550,610095,196.604180
2025-04-22 13:40:00+00:00,197.2500,197.5074,196.6200,9144,196.6800,596526,197.072204
2025-04-22 13:45:00+00:00,197.5600,197.8200,197.2650,10091,197.2800,582525,197.589522
2025-04-22 13:50:00+00:00,197.4500,197.5700,197.1310,7942,197.5500,492395,197.342011
2025-04-22 13:55:00+00:00,197.8200,197.8700,197.2300,7826,197.4600,459424,197.516093
2025-04-22 14:00:00+00:00,198.4750,198.5500,197.6200,10714,197.8300,621217,198.067055
2025-04-22 14:05:00+00:00,198.6600,198.8000,198.2150,9325,198.4800,554537,198.584153
2025-04-22 14:10:00+00:00,198.1742,198.9400,198.0800,9661,198.6608,656148,198.558708
2025-04-22 14:15:00+00:00,197.9300,198.1900,197.7500,7027,198.1800,445037,197.959455
2025-04-22 14:20:00+00:00,198.0750,198.2700,197.8800,6371,197.9600,398020,198.072451
2025-04-22 14:25:00+00:00,198.1100,198.1500,197.6696,6179,198.0800,357370,197.882693
2025-04-22 14:30:00+00:00,198.2500,198.2500,197.6700,5735,198.1200,355510,198.005039
2025-04-22 14:35:00+00:00,198.7150,198.7300,198.2100,6988,198.2500,370933,198.435724
2025-04-22 14:40:00+00:00,198.4950,198.8100,198.4150,7053,198.7150,387173,198.601446
2025-04-22 14:45:00+00:00,198.8902,199.1000,198.3200,8846,198.4950,626458,198.880892
2025-04-22 14:50:00+00:00,199.0750,199.1400,198.5700,7702,198.8950,527611,198.888460
2025-04-22 14:55:00+00:00,199.3001,199.3900,199.0500,7059,199.0650,508155,199.229769
2025-04-22 15:00:00+00:00,199.1700,199.3400,198.9200,5954,199.3100,400203,199.134576
2025-04-22 15:05:00+00:00,199.3800,199.4700,199.1600,5423,199.1700,351682,199.337137
2025-04-22 15:10:00+00:00,199.3950,199.4600,199.1500,5812,199.3716,380578,199.322527
2025-04-22 15:15:00+00:00,198.9950,199.4900,198.8700,8302,199.4000,494054,199.232567
2025-04-22 15:20:00+00:00,199.4961,199.5300,198.7700,6297,199.0100,445039,199.251809
2025-04-22 15:25:00+00:00,198.8300,199.5500,198.8100,5794,199.5200,374914,199.209354
2025-04-22 15:30:00+00:00,198.8200,198.8513,198.5900,5532,198.8250,344558,198.704301
2025-04-22 15:35:00+00:00,198.3550,198.8300,198.2600,5972,198.8200,346053,198.503004

In [12]:
data = bars[['vwap', 'trade_count']]

In [13]:
data

                                 vwap  trade_count
timestamp
2025-04-22 12:40:00+00:00  194.587820          245
2025-04-22 12:45:00+00:00  194.791148          314
2025-04-22 12:50:00+00:00  194.947509          307
2025-04-22 12:55:00+00:00  195.150332          265
2025-04-22 13:00:00+00:00  195.157991          278
2025-04-22 13:05:00+00:00  195.049877          347
2025-04-22 13:10:00+00:00  194.948749          379
2025-04-22 13:15:00+00:00  194.997318          237
2025-04-22 13:20:00+00:00  195.006702          471
2025-04-22 13:25:00+00:00  195.775389         1039
2025-04-22 13:30:00+00:00  196.528102        26689
2025-04-22 13:35:00+00:00  196.604180        10280
2025-04-22 13:40:00+00:00  197.072204         9144
2025-04-22 13:45:00+00:00  197.589522        10091
2025-04-22 13:50:00+00:00  197.342011         7942
2025-04-22 13:55:00+00:00  197.516093         7826
2025-04-22 14:00:00+00:00  198.067055        10714
2025-04-22 14:05:00+00:00  198.584153         9325
2025-04-22 14:10:00+00:00  198.558708         9661
2025-04-22 14:15:00+00:00  197.959455         7027
2025-04-22 14:20:00+00:00  198.072451         6371
2025-04-22 14:25:00+00:00  197.882693         6179
2025-04-22 14:30:00+00:00  198.005039         5735
2025-04-22 14:35:00+00:00  198.435724         6988
2025-04-22 14:40:00+00:00  198.601446         7053
2025-04-22 14:45:00+00:00  198.880892         8846
2025-04-22 14:50:00+00:00  198.888460         7702
2025-04-22 14:55:00+00:00  199.229769         7059
2025-04-22 15:00:00+00:00  199.134576         5954
2025-04-22 15:05:00+00:00  199.337137         5423
2025-04-22 15:10:00+00:00  199.322527         5812
2025-04-22 15:15:00+00:00  199.232567         8302
2025-04-22 15:20:00+00:00  199.251809         6297
2025-04-22 15:25:00+00:00  199.209354         5794
2025-04-22 15:30:00+00:00  198.704301         5532
2025-04-22 15:35:00+00:00  198.503004         5972

In [14]:
scaler = joblib.load("/content/drive/MyDrive/AI Financial Analisys/Summer Project/Live Trading/minmax_ds=sip+s=AAPL+mp=False+sd=2016-01-1+ed=2024-12-30+tf=5Min.pkl")

In [34]:
X_VWAP = data[['vwap']].to_numpy()

X_VWAP_scaled = scaler.transform(X_VWAP)

In [35]:
X_VWAP_scaled

array([[0.24718667],
       [0.24766444],
       [0.24803185],
       [0.24850844],
       [0.24852644],
       [0.24827239],
       [0.24803477],
       [0.24814889],
       [0.24817094],
       [0.24997717],
       [0.25174587],
       [0.25192463],
       [0.25302438],
       [0.25423995],
       [0.25365836],
       [0.25406741],
       [0.25536204],
       [0.25657709],
       [0.2565173 ],
       [0.2551092 ],
       [0.25537471],
       [0.25492883],
       [0.25521631],
       [0.25622832],
       [0.25661773],
       [0.25727436],
       [0.25729214],
       [0.25809413],
       [0.25787045],
       [0.25834642],
       [0.25831209],
       [0.25810071],
       [0.25814592],
       [0.25804616],
       [0.25685941],
       [0.25638641]])

In [30]:
X_Trade_Count = data[['trade_count']].to_numpy()

In [31]:
X_Trade_Count

array([[  245],
       [  314],
       [  307],
       [  265],
       [  278],
       [  347],
       [  379],
       [  237],
       [  471],
       [ 1039],
       [26689],
       [10280],
       [ 9144],
       [10091],
       [ 7942],
       [ 7826],
       [10714],
       [ 9325],
       [ 9661],
       [ 7027],
       [ 6371],
       [ 6179],
       [ 5735],
       [ 6988],
       [ 7053],
       [ 8846],
       [ 7702],
       [ 7059],
       [ 5954],
       [ 5423],
       [ 5812],
       [ 8302],
       [ 6297],
       [ 5794],
       [ 5532],
       [ 5972]])

In [19]:
X_combined = np.concatenate([X_VWAP_scaled, X_Trade_Count], axis=1)

In [20]:
X_combined

array([[2.47186671e-01, 2.45000000e+02],
       [2.47664443e-01, 3.14000000e+02],
       [2.48031853e-01, 3.07000000e+02],
       [2.48508439e-01, 2.65000000e+02],
       [2.48526435e-01, 2.78000000e+02],
       [2.48272393e-01, 3.47000000e+02],
       [2.48034767e-01, 3.79000000e+02],
       [2.48148892e-01, 2.37000000e+02],
       [2.48170943e-01, 4.71000000e+02],
       [2.49977172e-01, 1.03900000e+03],
       [2.51745866e-01, 2.66890000e+04],
       [2.51924631e-01, 1.02800000e+04],
       [2.53024375e-01, 9.14400000e+03],
       [2.54239948e-01, 1.00910000e+04],
       [2.53658357e-01, 7.94200000e+03],
       [2.54067408e-01, 7.82600000e+03],
       [2.55362036e-01, 1.07140000e+04],
       [2.56577092e-01, 9.32500000e+03],
       [2.56517302e-01, 9.66100000e+03],
       [2.55109202e-01, 7.02700000e+03],
       [2.55374715e-01, 6.37100000e+03],
       [2.54928829e-01, 6.17900000e+03],
       [2.55216313e-01, 5.73500000e+03],
       [2.56228319e-01, 6.98800000e+03],
       [2.56617726e-01, 7.05300000e+03],
       [2.57274357e-01, 8.84600000e+03],
       [2.57292140e-01, 7.70200000e+03],
       [2.58094134e-01, 7.05900000e+03],
       [2.57870453e-01, 5.95400000e+03],
       [2.58346423e-01, 5.42300000e+03],
       [2.58312093e-01, 5.81200000e+03],
       [2.58100708e-01, 8.30200000e+03],
       [2.58145922e-01, 6.29700000e+03],
       [2.58046163e-01, 5.79400000e+03],
       [2.56859410e-01, 5.53200000e+03],
       [2.56386411e-01, 5.97200000e+03]])

In [21]:
X_Tensor = np.expand_dims(X_combined, axis=0)

In [22]:
X_Tensor

array([[[2.47186671e-01, 2.45000000e+02],
        [2.47664443e-01, 3.14000000e+02],
        [2.48031853e-01, 3.07000000e+02],
        [2.48508439e-01, 2.65000000e+02],
        [2.48526435e-01, 2.78000000e+02],
        [2.48272393e-01, 3.47000000e+02],
        [2.48034767e-01, 3.79000000e+02],
        [2.48148892e-01, 2.37000000e+02],
        [2.48170943e-01, 4.71000000e+02],
        [2.49977172e-01, 1.03900000e+03],
        [2.51745866e-01, 2.66890000e+04],
        [2.51924631e-01, 1.02800000e+04],
        [2.53024375e-01, 9.14400000e+03],
        [2.54239948e-01, 1.00910000e+04],
        [2.53658357e-01, 7.94200000e+03],
        [2.54067408e-01, 7.82600000e+03],
        [2.55362036e-01, 1.07140000e+04],
        [2.56577092e-01, 9.32500000e+03],
        [2.56517302e-01, 9.66100000e+03],
        [2.55109202e-01, 7.02700000e+03],
        [2.55374715e-01, 6.37100000e+03],
        [2.54928829e-01, 6.17900000e+03],
        [2.55216313e-01, 5.73500000e+03],
        [2.56228319e-01, 6.98800000e+03],
        [2.56617726e-01, 7.05300000e+03],
        [2.57274357e-01, 8.84600000e+03],
        [2.57292140e-01, 7.70200000e+03],
        [2.58094134e-01, 7.05900000e+03],
        [2.57870453e-01, 5.95400000e+03],
        [2.58346423e-01, 5.42300000e+03],
        [2.58312093e-01, 5.81200000e+03],
        [2.58100708e-01, 8.30200000e+03],
        [2.58145922e-01, 6.29700000e+03],
        [2.58046163e-01, 5.79400000e+03],
        [2.56859410e-01, 5.53200000e+03],
        [2.56386411e-01, 5.97200000e+03]]])

In [23]:
model = load_model("/content/drive/MyDrive/AI Financial Analisys/Summer Project/Live Trading/ds=sip+s=AAPL+mp=False+sd=2016-01-1+ed=2024-12-30+tf=5Min+fm=vwap+sm=trade_count+tm=+r=36+sort=False+rfm=False+rsm=False+rtm=False+d=+st=minmax+cts=[0]+Lb=True+e=500+es=True+cb=val_accuracy+p=100+bs=128+tl=0.41606152057647705+ta=0.8365758657455444.keras")

In [24]:
predictions = model.predict(X_Tensor)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 653ms/step

In [25]:
predictions

array([[0.29987508]], dtype=float32)

In [26]:
decisive_sensibility = 0.5

predicted_classes = (predictions >= decisive_sensibility).astype(int)

In [27]:
print(predictions)
print(predicted_classes)

[[0.29987508]]
[[0]]