In [39]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [40]:
pip install alpaca-trade-api

Requirement already satisfied: alpaca-trade-api in /usr/local/lib/python3.11/dist-packages (3.2.0)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.2.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.0.2)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.32.3)
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.8.0)
Requirement already satisfied: websockets<11,>=9.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (10.4)
Requirement already satisfied: msgpack==1.0.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.0.3)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (3.11.15)
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from deprecation==2.1.0->alpaca-trade-api) (24.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.20.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (2025.4.26)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.18.1->alpaca-trade-api) (1.17.0)

In [41]:
pip install polygon-api-client

Requirement already satisfied: polygon-api-client in /usr/local/lib/python3.11/dist-packages (1.14.5)
Requirement already satisfied: certifi<2026.0.0,>=2022.5.18 in /usr/local/lib/python3.11/dist-packages (from polygon-api-client) (2025.4.26)
Requirement already satisfied: urllib3<3.0.0,>=1.26.9 in /usr/local/lib/python3.11/dist-packages (from polygon-api-client) (1.26.20)
Requirement already satisfied: websockets<15.0,>=10.3 in /usr/local/lib/python3.11/dist-packages (from polygon-api-client) (10.4)

In [42]:
import alpaca_trade_api as tradeapi
from polygon import RESTClient
import pandas as pd
import time
from datetime import datetime, timedelta, timezone
import tensorflow as tf
from tensorflow.keras.models import load_model
import joblib
import numpy as np

In [43]:
ALPACA_API_KEY = "AK1RX6F8W6QX207XPLDF"
ALPACA_SECRET_KEY = "WaPoTTxkQBGzC51LajCdyw8Pl6svbINa9eDu9TMK"
ALPACA_BASE_URL = "https://api.alpaca.markets"

POLYGON_API_KEY = "Gkm8qM_seLdMVw3YRiSBODhwwmpPPpn4"

In [44]:
# Inicializa a API Alpaca com as credenciais lidas do arquivo
api = tradeapi.REST(ALPACA_API_KEY, ALPACA_SECRET_KEY, ALPACA_BASE_URL, api_version='v2')

In [45]:
clock = api.get_clock()

In [46]:
clock

Clock({   'is_open': True,
    'next_close': '2025-05-09T16:00:00-04:00',
    'next_open': '2025-05-12T09:30:00-04:00',
    'timestamp': '2025-05-09T14:20:27.561349746-04:00'})

In [47]:
client = RESTClient(POLYGON_API_KEY)

In [48]:
status = client.get_market_status()

In [49]:
status

MarketStatus(after_hours=False, currencies=MarketCurrencies(crypto='open', fx='open'), early_hours=False, exchanges=MarketExchanges(nasdaq='open', nyse='open', otc='open'), indicesGroups=MarketIndices(s_and_p='open', societe_generale='open', cgi='open', msci='open', ftse_russell='open', mstar='open', mstarc='open', cccy='open', nasdaq='open', dow_jones='open'), market='open', server_time='2025-05-09T14:20:27-04:00')

In [50]:
if status.market == "open":
    print("The market is open regular hours.")
elif status.early_hours:
    print("The market is open pre hours.")
elif status.after_hours:
    print("The market is open after hours.")
else:
    print("The market is closed.")

The market is open regular hours.

In [51]:
delayed_safe_df = 5

now   = datetime.now(timezone.utc)
start = (now - timedelta(days=delayed_safe_df)).isoformat()

print("Now (UTC):", now)
print("Start (UTC):", start)

Now (UTC): 2025-05-09 18:20:27.865724+00:00
Start (UTC): 2025-05-04T18:20:27.865724+00:00

In [52]:
symbol = "AAPL"
timeframe = "5Min"
data_source = "sip"
dataset_size = 36

In [53]:
# Fetch the historical data
bars = api.get_bars(
    symbol,
    timeframe,
    start,
    feed=data_source
).df.tail(dataset_size)

In [54]:
bars

,close,high,low,trade_count,open,volume,vwap
timestamp,,,,,,,
2025-05-09 15:10:00+00:00,198.8900,198.9050,198.3100,5045,198.8800,433739,198.701376
2025-05-09 15:15:00+00:00,198.8200,199.1800,198.6900,4534,198.8900,401799,198.938096
2025-05-09 15:20:00+00:00,198.3900,198.8397,198.3558,4775,198.8200,334010,198.546657
2025-05-09 15:25:00+00:00,198.4300,198.5200,198.2000,4234,198.3801,328932,198.374568
2025-05-09 15:30:00+00:00,198.5501,198.5700,198.1400,4738,198.4250,332396,198.287617
2025-05-09 15:35:00+00:00,198.3500,198.6640,198.3100,4100,198.5700,266078,198.496335
2025-05-09 15:40:00+00:00,198.5279,198.5650,198.2300,3184,198.3500,203919,198.434810
2025-05-09 15:45:00+00:00,198.6836,198.7804,198.3600,4153,198.5300,264342,198.604140
2025-05-09 15:50:00+00:00,198.7000,199.0100,198.5600,3985,198.6700,263119,198.870335
2025-05-09 15:55:00+00:00,198.7585,198.7699,198.5450,3096,198.6700,205484,198.678272
2025-05-09 16:00:00+00:00,198.1000,198.7597,198.0806,4292,198.7200,296315,198.402345
2025-05-09 16:05:00+00:00,198.0602,198.3100,198.0300,3606,198.1000,277638,198.171982
2025-05-09 16:10:00+00:00,198.4700,198.4900,197.9300,4317,198.0700,296698,198.141923
2025-05-09 16:15:00+00:00,198.4000,198.6600,198.2700,3825,198.4700,218020,198.440664
2025-05-09 16:20:00+00:00,198.3699,198.5000,198.2700,2644,198.3900,124179,198.371650
2025-05-09 16:25:00+00:00,198.1350,198.3599,198.1100,2713,198.3200,143487,198.225130
2025-05-09 16:30:00+00:00,198.1701,198.2400,198.0400,2912,198.1300,179693,198.133959
2025-05-09 16:35:00+00:00,197.8500,198.3900,197.8350,3887,198.1714,256513,198.139396
2025-05-09 16:40:00+00:00,197.8994,198.0800,197.8400,3062,197.8400,199514,197.972035
2025-05-09 16:45:00+00:00,197.8600,198.0107,197.7500,3946,197.8900,270951,197.896311
2025-05-09 16:50:00+00:00,198.1850,198.1900,197.8300,3563,197.8600,240979,197.972536
2025-05-09 16:55:00+00:00,197.9700,198.2899,197.9600,3321,198.1850,307586,198.135935
2025-05-09 17:00:00+00:00,197.9900,198.1600,197.8800,3894,197.9600,341547,198.037360
2025-05-09 17:05:00+00:00,198.3200,198.3200,197.7800,3739,198.0000,223049,198.044486
2025-05-09 17:10:00+00:00,198.0650,198.4500,198.0500,3331,198.3200,201565,198.311950
2025-05-09 17:15:00+00:00,198.1600,198.3900,198.0600,3123,198.0600,212769,198.241746
2025-05-09 17:20:00+00:00,198.2014,198.4100,197.6000,7344,198.1750,443769,198.061876
2025-05-09 17:25:00+00:00,198.1400,198.4000,198.1400,3022,198.2100,176484,198.249133
2025-05-09 17:30:00+00:00,197.9600,198.2750,197.9100,3803,198.1450,211336,198.071164
2025-05-09 17:35:00+00:00,198.3100,198.3200,197.9200,3157,197.9600,205914,198.114890
2025-05-09 17:40:00+00:00,198.4600,198.5350,198.2100,3432,198.2900,225831,198.380602
2025-05-09 17:45:00+00:00,198.6898,198.7900,198.4503,2944,198.4600,201229,198.663166
2025-05-09 17:50:00+00:00,198.5800,198.6994,198.4742,3004,198.6800,184177,198.580308
2025-05-09 17:55:00+00:00,198.7057,198.8150,198.5668,2800,198.5700,202613,198.707401
2025-05-09 18:00:00+00:00,198.7000,198.9000,198.6700,2910,198.7100,186773,198.797748
2025-05-09 18:05:00+00:00,198.8300,198.9900,198.6400,3209,198.7100,219132,198.874009

In [55]:
data = bars[['vwap', 'trade_count']]

In [56]:
data

                                 vwap  trade_count
timestamp
2025-05-09 15:10:00+00:00  198.701376         5045
2025-05-09 15:15:00+00:00  198.938096         4534
2025-05-09 15:20:00+00:00  198.546657         4775
2025-05-09 15:25:00+00:00  198.374568         4234
2025-05-09 15:30:00+00:00  198.287617         4738
2025-05-09 15:35:00+00:00  198.496335         4100
2025-05-09 15:40:00+00:00  198.434810         3184
2025-05-09 15:45:00+00:00  198.604140         4153
2025-05-09 15:50:00+00:00  198.870335         3985
2025-05-09 15:55:00+00:00  198.678272         3096
2025-05-09 16:00:00+00:00  198.402345         4292
2025-05-09 16:05:00+00:00  198.171982         3606
2025-05-09 16:10:00+00:00  198.141923         4317
2025-05-09 16:15:00+00:00  198.440664         3825
2025-05-09 16:20:00+00:00  198.371650         2644
2025-05-09 16:25:00+00:00  198.225130         2713
2025-05-09 16:30:00+00:00  198.133959         2912
2025-05-09 16:35:00+00:00  198.139396         3887
2025-05-09 16:40:00+00:00  197.972035         3062
2025-05-09 16:45:00+00:00  197.896311         3946
2025-05-09 16:50:00+00:00  197.972536         3563
2025-05-09 16:55:00+00:00  198.135935         3321
2025-05-09 17:00:00+00:00  198.037360         3894
2025-05-09 17:05:00+00:00  198.044486         3739
2025-05-09 17:10:00+00:00  198.311950         3331
2025-05-09 17:15:00+00:00  198.241746         3123
2025-05-09 17:20:00+00:00  198.061876         7344
2025-05-09 17:25:00+00:00  198.249133         3022
2025-05-09 17:30:00+00:00  198.071164         3803
2025-05-09 17:35:00+00:00  198.114890         3157
2025-05-09 17:40:00+00:00  198.380602         3432
2025-05-09 17:45:00+00:00  198.663166         2944
2025-05-09 17:50:00+00:00  198.580308         3004
2025-05-09 17:55:00+00:00  198.707401         2800
2025-05-09 18:00:00+00:00  198.797748         2910
2025-05-09 18:05:00+00:00  198.874009         3209

In [57]:
scaler = joblib.load("/content/drive/MyDrive/AI Financial Analisys/Summer Project/Live Trading/minmax_ds=sip+s=AAPL+mp=False+sd=2016-01-1+ed=2024-12-30+tf=5Min.pkl")

In [58]:
X_VWAP = data[['vwap']].to_numpy()

X_VWAP_scaled = scaler.transform(X_VWAP)

In [59]:
X_VWAP_scaled

array([[0.25685254],
       [0.25740877],
       [0.25648898],
       [0.25608462],
       [0.2558803 ],
       [0.25637074],
       [0.25622617],
       [0.25662406],
       [0.25724955],
       [0.25679825],
       [0.25614989],
       [0.25560859],
       [0.25553796],
       [0.25623993],
       [0.25607776],
       [0.25573347],
       [0.25551924],
       [0.25553202],
       [0.25513876],
       [0.25496083],
       [0.25513994],
       [0.25552389],
       [0.25529226],
       [0.255309  ],
       [0.25593748],
       [0.25577252],
       [0.25534987],
       [0.25578988],
       [0.25537169],
       [0.25547444],
       [0.2560988 ],
       [0.25676275],
       [0.25656806],
       [0.25686669],
       [0.25707899],
       [0.25725818]])

In [60]:
X_Trade_Count = data[['trade_count']].to_numpy()

In [61]:
X_Trade_Count

array([[5045],
       [4534],
       [4775],
       [4234],
       [4738],
       [4100],
       [3184],
       [4153],
       [3985],
       [3096],
       [4292],
       [3606],
       [4317],
       [3825],
       [2644],
       [2713],
       [2912],
       [3887],
       [3062],
       [3946],
       [3563],
       [3321],
       [3894],
       [3739],
       [3331],
       [3123],
       [7344],
       [3022],
       [3803],
       [3157],
       [3432],
       [2944],
       [3004],
       [2800],
       [2910],
       [3209]])

In [62]:
X_combined = np.concatenate([X_VWAP_scaled, X_Trade_Count], axis=1)

In [63]:
X_combined

array([[2.56852537e-01, 5.04500000e+03],
       [2.57408772e-01, 4.53400000e+03],
       [2.56488985e-01, 4.77500000e+03],
       [2.56084617e-01, 4.23400000e+03],
       [2.55880303e-01, 4.73800000e+03],
       [2.56370740e-01, 4.10000000e+03],
       [2.56226171e-01, 3.18400000e+03],
       [2.56624056e-01, 4.15300000e+03],
       [2.57249550e-01, 3.98500000e+03],
       [2.56798249e-01, 3.09600000e+03],
       [2.56149887e-01, 4.29200000e+03],
       [2.55608589e-01, 3.60600000e+03],
       [2.55537957e-01, 4.31700000e+03],
       [2.56239927e-01, 3.82500000e+03],
       [2.56077761e-01, 2.64400000e+03],
       [2.55733474e-01, 2.71300000e+03],
       [2.55519244e-01, 2.91200000e+03],
       [2.55532020e-01, 3.88700000e+03],
       [2.55138762e-01, 3.06200000e+03],
       [2.54960828e-01, 3.94600000e+03],
       [2.55139939e-01, 3.56300000e+03],
       [2.55523887e-01, 3.32100000e+03],
       [2.55292260e-01, 3.89400000e+03],
       [2.55309004e-01, 3.73900000e+03],
       [2.55937480e-01, 3.33100000e+03],
       [2.55772518e-01, 3.12300000e+03],
       [2.55349866e-01, 7.34400000e+03],
       [2.55789875e-01, 3.02200000e+03],
       [2.55371691e-01, 3.80300000e+03],
       [2.55474436e-01, 3.15700000e+03],
       [2.56098796e-01, 3.43200000e+03],
       [2.56762753e-01, 2.94400000e+03],
       [2.56568057e-01, 3.00400000e+03],
       [2.56866695e-01, 2.80000000e+03],
       [2.57078988e-01, 2.91000000e+03],
       [2.57258183e-01, 3.20900000e+03]])

In [64]:
X_Tensor = np.expand_dims(X_combined, axis=0)

In [65]:
X_Tensor

array([[[2.56852537e-01, 5.04500000e+03],
        [2.57408772e-01, 4.53400000e+03],
        [2.56488985e-01, 4.77500000e+03],
        [2.56084617e-01, 4.23400000e+03],
        [2.55880303e-01, 4.73800000e+03],
        [2.56370740e-01, 4.10000000e+03],
        [2.56226171e-01, 3.18400000e+03],
        [2.56624056e-01, 4.15300000e+03],
        [2.57249550e-01, 3.98500000e+03],
        [2.56798249e-01, 3.09600000e+03],
        [2.56149887e-01, 4.29200000e+03],
        [2.55608589e-01, 3.60600000e+03],
        [2.55537957e-01, 4.31700000e+03],
        [2.56239927e-01, 3.82500000e+03],
        [2.56077761e-01, 2.64400000e+03],
        [2.55733474e-01, 2.71300000e+03],
        [2.55519244e-01, 2.91200000e+03],
        [2.55532020e-01, 3.88700000e+03],
        [2.55138762e-01, 3.06200000e+03],
        [2.54960828e-01, 3.94600000e+03],
        [2.55139939e-01, 3.56300000e+03],
        [2.55523887e-01, 3.32100000e+03],
        [2.55292260e-01, 3.89400000e+03],
        [2.55309004e-01, 3.73900000e+03],
        [2.55937480e-01, 3.33100000e+03],
        [2.55772518e-01, 3.12300000e+03],
        [2.55349866e-01, 7.34400000e+03],
        [2.55789875e-01, 3.02200000e+03],
        [2.55371691e-01, 3.80300000e+03],
        [2.55474436e-01, 3.15700000e+03],
        [2.56098796e-01, 3.43200000e+03],
        [2.56762753e-01, 2.94400000e+03],
        [2.56568057e-01, 3.00400000e+03],
        [2.56866695e-01, 2.80000000e+03],
        [2.57078988e-01, 2.91000000e+03],
        [2.57258183e-01, 3.20900000e+03]]])

In [66]:
model = load_model("/content/drive/MyDrive/AI Financial Analisys/Summer Project/Live Trading/ds=sip+s=AAPL+mp=False+sd=2016-01-1+ed=2024-12-30+tf=5Min+fm=vwap+sm=trade_count+tm=+r=36+sort=False+rfm=False+rsm=False+rtm=False+d=+st=minmax+cts=[0]+Lb=True+e=500+es=True+cb=val_accuracy+p=100+bs=128+tl=0.41606152057647705+ta=0.8365758657455444.keras")

In [67]:
predictions = model.predict(X_Tensor)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 651ms/step

In [68]:
predictions

array([[0.24083064]], dtype=float32)

In [69]:
decisive_sensibility = 0.5

predicted_classes = (predictions >= decisive_sensibility).astype(int)

In [70]:
print(predictions)
print(predicted_classes)

[[0.24083064]]
[[0]]

In [71]:
def add_hours_skipping_night(start: pd.Timestamp, hours: float) -> pd.Timestamp:
    """
    Add `hours` to `start`, but never count any time between 00:00 and 08:00.
    """
    current = start
    remaining = hours
    while remaining > 0:
        # 1) If we're in the blackout (00:00–08:00), jump to 08:00 that same day
        if current.hour < 8:
            current = current.normalize() + timedelta(hours=8)

        # 2) Otherwise, we have until midnight to work with
        end_of_day = current.normalize() + timedelta(days=1)
        available = (end_of_day - current).total_seconds() / 3600.0

        # 3) Consume whichever is smaller: what's left today, or what you still need
        to_add = min(available, remaining)
        current += timedelta(hours=to_add)
        remaining -= to_add

        # 4) If you still have time to add, skip the next 00:00–08:00 and loop
        if remaining > 0:
            current = current.normalize() + timedelta(days=1, hours=8)

    return current

In [ ]:
# --- usage on your DataFrame: ---
last_ts = data.index[-1]        # or data.tail(1).index[0]
end_time_prediction = add_hours_skipping_night(last_ts, 3)

In [73]:
start_str = last_ts.strftime('%b %-d, %Y at %-I:%M %p')       # e.g. “May 9, 2025 at 10:30 PM”
end_str   = end_time_prediction.strftime('%b %-d, %Y at %-I:%M %p')
print(f"Prediction valid from {start_str} until {end_str}.")

Prediction valid from May 9, 2025 at 6:05 PM until May 9, 2025 at 9:05 PM.